// App con anti-cache + tabs de ETAPAS + grupos
const DATA = {
  matches:'data/matches.json', predictions:'data/predictions.json', results:'data/results.json',
  bonusPicks:'data/bonus_picks.json', bonusActual:'data/bonus_actual.json', groups:'data/groups.json',
  fixtures:'data/stage_fixtures.json', stagePreds:'data/stage_predictions.json', config:'data/config.json'
};
const VERSION='20260305-STAGES-FULL';
const bust=(url)=> url+(url.includes('?')?'&':'?')+'v='+VERSION+'&t='+Date.now();
let STATE={ matches:[], participants:[], results:[], resultsById:new Map(), bonus:{picks:[],actual:{}}, groups:null, fixtures:null, stagePreds:[], config:{stages:{}} };

async function safeJson(url){ const r=await fetch(bust(url),{cache:'no-store'}); if(!r.ok) throw new Error(url+': '+r.status); return r.json(); }
async function loadAll(){
  const [m,p,r,bp,ba,g,f,sp,c] = await Promise.all([
    fetch(bust(DATA.matches),{cache:'no-store'}).then(x=>x.ok?x.json():{matches:[]}),
    fetch(bust(DATA.predictions),{cache:'no-store'}).then(x=>x.ok?x.json():{participants:[]}),
    safeJson(DATA.results).catch(()=>({results:[]})),
    fetch(bust(DATA.bonusPicks),{cache:'no-store'}).then(x=>x.ok?x.json():{participants:[]}),
    fetch(bust(DATA.bonusActual),{cache:'no-store'}).then(x=>x.ok?x.json():{}),
    fetch(bust(DATA.groups),{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null),
    safeJson(DATA.fixtures), safeJson(DATA.stagePreds), safeJson(DATA.config)
  ]);
  STATE.matches=m.matches||[]; STATE.participants=(p.participants||[]).slice().sort((a,b)=>a.name?.localeCompare(b.name)??0);
  STATE.results=r.results||[]; STATE.resultsById=new Map(STATE.results.map(x=>[x.matchId,x]));
  STATE.bonus.picks=bp.participants||[]; STATE.bonus.actual=ba||{}; STATE.groups=g && (g.groups||g) ? (g.groups||g):null;
  STATE.fixtures=f||null; STATE.stagePreds=(sp.participants||[]); STATE.config=c||{stages:{}};
}

function outcome(h,a){ if(h>a) return 'H'; if(h<a) return 'A'; return 'D'; }
function pointsPerMatch(pred, actual){ if(!actual) return {pts:0,label:'Sin resultado'}; const {homeGoals:ah,awayGoals:aa}=actual; const ph=pred?.homeGoalsPred, pa=pred?.awayGoalsPred; if(ph==null||pa==null) return {pts:0,label:'Sin predicción'}; if(ph===ah&&pa===aa) return {pts:5,label:'Marcador exacto (5)'}; const po=outcome(ph,pa), ao=outcome(ah,aa); const three=(ao!=='D'&&po===ao&&((ao==='H'&&ph===ah)||(ao==='A'&&pa===aa))&&(ph!==ah||pa!==aa))||(ao==='D'&&po==='D'&&(ph!==ah)); if(three) return {pts:3,label:'Ganador y sus goles / empate distinto (3)'}; if(po===ao) return {pts:2,label:'Resultado correcto (2)'}; if((ph===ah)^(pa===aa)) return {pts:1,label:'Acierta goles de un equipo (1)'}; return {pts:0,label:'No acierta (0)'}; }
const BONUS_WEIGHTS={roundOf32:2,roundOf16:5,quarterfinals:10,semifinals:15,thirdPlace:17,final:20};
function pointsBonusForParticipant(email){ const picks=STATE.bonus.picks.find(x=>x.email===email)?.picks||{}; const actual=STATE.bonus.actual||{}; let total=0; for(const k of Object.keys(BONUS_WEIGHTS)){ const w=BONUS_WEIGHTS[k]; const wanted=new Set((picks[k]||[]).map(x=>x.trim().toLowerCase())); const real=new Set((actual[k]||[]).map(x=>x.trim().toLowerCase())); let hit=0; for(const t of wanted) if(real.has(t)) hit++; total+=hit*w; } return {total}; }

function renderParticipantByEmail(email){ const p=STATE.participants.find(x=>x.email===email); if(!p){ document.getElementById('matches').innerHTML=''; document.getElementById('s_name').textContent='—'; document.getElementById('s_match_pts').textContent=0; document.getElementById('s_bonus').textContent=0; document.getElementById('s_total').textContent=0; renderStages(null); return; } renderParticipant(p.name); }
function renderParticipant(qstr){ const q=(qstr||'').trim().toLowerCase(); const p=STATE.participants.find(x=>x.name?.toLowerCase().includes(q)||x.email?.toLowerCase().includes(q)); const matchesEl=document.getElementById('matches'); matchesEl.innerHTML=''; let matchPts=0; for(const m of STATE.matches){ const pred=p?.predictions?.find(pp=>pp.matchId===m.matchId)||{}; const actual=STATE.resultsById.get(m.matchId); const sc=pointsPerMatch(pred,actual); matchPts+=sc.pts; const div=document.createElement('div'); div.className='match'; div.innerHTML=`<div class="match__id">#${m.matchId}</div><div><div class="team"><span class="team__name">${m.homeTeam}</span><span class="badge">Pred: ${pred.homeGoalsPred??'—'} - ${pred.awayGoalsPred??'—'}</span></div><div class="team"><span class="team__name">${m.awayTeam}</span></div></div><div class="score"><div class="badge ${actual?'badge--ok':'badge--warn'}">Final: ${actual?`${actual.homeGoals} - ${actual.awayGoals}`:'—'}</div><div class="pts">+${sc.pts}</div></div>`; div.title=sc.label; matchesEl.appendChild(div);} const bonus=p?pointsBonusForParticipant(p.email):{total:0}; const total=matchPts+(bonus.total||0); document.getElementById('s_name').textContent=p?`${p.name}`:'—'; document.getElementById('s_match_pts').textContent=matchPts; document.getElementById('s_bonus').textContent=bonus.total||0; document.getElementById('s_total').textContent=total; renderStages(p); }

function matchPointsForParticipant(p){ let sum=0; for(const m of STATE.matches){ const pred=p?.predictions?.find(pp=>pp.matchId===m.matchId)||{}; const actual=STATE.resultsById.get(m.matchId); sum+=pointsPerMatch(pred,actual).pts; } return sum; }
function computeStandings(){ const rows=STATE.participants.map(p=>{ const matchPts=matchPointsForParticipant(p); const bonus=pointsBonusForParticipant(p.email); const total=matchPts+(bonus.total||0); return {name:p.name,email:p.email,matchPts,bonusPts:bonus.total||0,total};}); rows.sort((a,b)=>b.total-a.total||b.matchPts-a.matchPts||a.name.localeCompare(b.name)); return rows; }
function renderStandings(){ const tbody=document.querySelector('#standings tbody'); if(!tbody) return; tbody.innerHTML=''; computeStandings().forEach((r,i)=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td class="rank">${i+1}</td><td><div style="font-weight:700">${r.name}</div><div class="muted" style="font-size:12px">${r.email}</div></td><td class="center">${r.matchPts}</td><td class="center">${r.bonusPts}</td><td class="center" style="font-weight:700">${r.total}</td>`; tbody.appendChild(tr); }); }

// WORLD by groups
function computeGroupsTable(){ if(!STATE.groups) return null; const team2group=new Map(); for(const [g,list] of Object.entries(STATE.groups)){ (list||[]).forEach(t=>team2group.set(t,g)); } const perGroup=new Map(); function ensure(g,t){ if(!perGroup.has(g)) perGroup.set(g,new Map()); const m=perGroup.get(g); if(!m.has(t)) m.set(t,{team:t,PJ:0,G:0,E:0,P:0,GF:0,GC:0,GD:0,PTS:0}); return m.get(t);} for(const res of STATE.results){ const m=STATE.matches.find(x=>x.matchId===res.matchId); if(!m) continue; const gA=team2group.get(m.homeTeam), gB=team2group.get(m.awayTeam); if(!gA||!gB||gA!==gB) continue; const A=ensure(gA,m.homeTeam), B=ensure(gA,m.awayTeam); const hg=res.homeGoals, ag=res.awayGoals; A.PJ++; B.PJ++; A.GF+=hg; A.GC+=ag; B.GF+=ag; B.GC+=hg; if(hg>ag){ A.G++; A.PTS+=3; B.P++; } else if(hg<ag){ B.G++; B.PTS+=3; A.P++; } else { A.E++; B.E++; A.PTS++; B.PTS++; } } const out=[]; for(const [g,map] of perGroup.entries()){ const arr=[...map.values()].map(t=>({...t,GD:t.GF-t.GC})); arr.sort((a,b)=> b.PTS-a.PTS||b.GD-a.GD||b.GF-a.GF||a.team.localeCompare(b.team)); out.push({group:g,rows:arr}); } for(const [g,list] of Object.entries(STATE.groups)){ const found=out.find(x=>x.group===g); const rows=found?found.rows:[]; const present=new Set(rows.map(r=>r.team)); for(const t of list){ if(!present.has(t)) rows.push({team:t,PJ:0,G:0,E:0,P:0,GF:0,GC:0,GD:0,PTS:0}); } rows.sort((a,b)=> b.PTS-a.PTS||b.GD-a.GD||b.GF-a.GF||a.team.localeCompare(b.team)); if(!found) out.push({group:g,rows}); } out.sort((a,b)=> a.group.localeCompare(b.group,'es')); return out; }
function renderWorldByGroups(){ const host=document.getElementById('world_groups'); const hint=document.getElementById('world_hint'); if(!host) return; host.innerHTML=''; if(!STATE.groups){ hint.style.display='block'; return; } hint.style.display='none'; const data=computeGroupsTable(); for(const g of data){ const wrap=document.createElement('div'); wrap.className='group'; wrap.innerHTML=`<div class="group__hdr"><div class="group__title">${g.group}</div></div>`; const tableWrap=document.createElement('div'); tableWrap.className='table-wrap'; const table=document.createElement('table'); table.className='table'; table.innerHTML=`<thead><tr><th>Pos</th><th>Equipo</th><th class="center">PJ</th><th class="center">G</th><th class="center">E</th><th class="center">P</th><th class="center">GF</th><th class="center">GC</th><th class="center">DG</th><th class="center">Pts</th></tr></thead><tbody></tbody>`; const tbody=table.querySelector('tbody'); g.rows.forEach((r,idx)=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td class="rank">${idx+1}</td><td>${r.team}</td><td class="center">${r.PJ}</td><td class="center">${r.G}</td><td class="center">${r.E}</td><td class="center">${r.P}</td><td class="center">${r.GF}</td><td class="center">${r.GC}</td><td class="center">${r.GD}</td><td class="center" style="font-weight:700">${r.PTS}</td>`; tbody.appendChild(tr); }); tableWrap.appendChild(table); wrap.appendChild(tableWrap); host.appendChild(wrap); } }

// === STAGES UI ===
function findStagePreds(email){ return STATE.stagePreds.find(x=>x.email===email); }
function stageEnabled(key){ return !!(STATE.config?.stages?.[key]?.enabled); }
function renderStage(containerId, stageKey, fixtureList, preds){ const host=document.getElementById(containerId); if(!host) return; host.innerHTML=''; if(!stageEnabled(stageKey)){ const banner=document.createElement('div'); banner.className='disabledBanner'; banner.textContent='Este formulario aún no está habilitado.'; host.appendChild(banner); return; } for(const m of fixtureList){ const row=document.createElement('div'); row.className='stage__match'; const p = preds?.find(pp=>pp.id===m.id); const hg = p?.homeGoals ?? '—'; const ag = p?.awayGoals ?? '—'; row.innerHTML = `<div class="stage__id">${m.id}</div><div><div class="teamrow"><span class="team__name">${m.home}</span></div><div class="teamrow"><span class="team__name">${m.away}</span></div></div><div class="scorefield"><span class="badge">Pred: ${hg} - ${ag}</span></div>`; host.appendChild(row);} }
function renderStages(p){ const sp = p ? findStagePreds(p.email) : null; renderStage('stage_r32','roundOf32', STATE.fixtures?.roundOf32||[], sp?.roundOf32||[]); renderStage('stage_r16','roundOf16', STATE.fixtures?.roundOf16||[], sp?.roundOf16||[]); renderStage('stage_qf','quarterfinals', STATE.fixtures?.quarterfinals||[], sp?.quarterfinals||[]); renderStage('stage_sf','semifinals', STATE.fixtures?.semifinals||[], sp?.semifinals||[]); renderStage('stage_3p','thirdPlace', STATE.fixtures?.thirdPlace||[], sp?.thirdPlace||[]); renderStage('stage_f','final', STATE.fixtures?.final||[], sp?.final||[]); }

function populateSelect(){ const sel=document.getElementById('sel'); if(!sel) return; sel.innerHTML='<option value="">— Selecciona —</option>'; for(const p of STATE.participants){ const opt=document.createElement('option'); opt.value=p.email; opt.textContent=p.name; sel.appendChild(opt);} sel.addEventListener('change', ()=>{ const v=sel.value; renderParticipantByEmail(v); }); }

function wire(){ const q=document.getElementById('q'); const btn=document.getElementById('btnSearch'); if(btn) btn.addEventListener('click', ()=>renderParticipant(q.value)); if(q) q.addEventListener('keypress', (e)=>{ if(e.key==='Enter'){ renderParticipant(q.value); }}); document.querySelectorAll('.tab').forEach(btn=>{ btn.addEventListener('click', ()=>{ document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); const target=btn.getAttribute('data-target'); document.querySelectorAll('.tabpanel').forEach(p=>{ if('#'+p.id===target){ p.classList.add('active'); p.removeAttribute('aria-hidden'); } else { p.classList.remove('active'); p.setAttribute('aria-hidden','true'); } }); if(target==='#tab-standings') renderStandings(); if(target==='#tab-world') renderWorldByGroups(); }); }); }

(async function(){ try{ await loadAll(); populateSelect(); wire(); } catch(err){ console.error('Error cargando datos:',err); alert('No se pudieron cargar los datos. Revisa /data/*.json'); } })();
